package com.cloudhaus.sensorapp.ui.animation.floatball

import androidx.compose.foundation.Canvas
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.mutableFloatStateOf
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberUpdatedState
import androidx.compose.runtime.withFrameNanos
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Rect
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.drawscope.DrawScope
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.graphics.drawscope.clipRect
import androidx.compose.ui.graphics.drawscope.withTransform
import kotlin.math.PI
import kotlin.math.exp
import kotlin.math.min
import kotlin.math.pow
import kotlin.math.sin
import kotlin.random.Random

// Generated by animation-composer/translator from animations/floatball/source.jsx,
// then ported by AI from the JSX procedural drawing using the Candle port as
// the style exemplar.

private const val TWO_PI = 6.2831855f
private val PI_F = PI.toFloat()

@Suppress("MemberVisibilityCanBePrivate")
data class FloatBallPalette(
    val glass: Color = Color(0xFFCFE3EC),
    val glassRim: Color = Color(0xFFFFFFFF),
    val glassShade: Color = Color(0xFF7FA3B3),
    val base: Color = Color(0xFF3A2F26),
    val baseRim: Color = Color(0xFF5B4A3C),
    val ball: Color = Color(0xFFAEFF6B),
    val ballHi: Color = Color(0xFFF4FFBD),
    val ballShade: Color = Color(0xFF91AB36),
    val flow: Color = Color(0xFF9DB8C4),
) {
    companion object {
        val Default = FloatBallPalette()
    }
}

@Suppress("MemberVisibilityCanBePrivate")
data class FloatBallConfig(
    val tubeOuterR: Float = 110f,
    val tubeWall: Float = 11f,
    val ballR: Float = 60f,
    val tubeHeightCap: Float = 1200f,
    val tubeHeightFraction: Float = 0.78f,
    /** Where the ball settles at full breath, as a fraction of yMax (1 = at the top). */
    val equilibriumFraction: Float = 0.85f,
    val verticalSpring: Float = 3.8f,
    val verticalDampBase: Float = 0.8f,
    /** Per-frame chance of a sudden vertical gust event. */
    val gustChance: Float = 0.04f,
    /** Seconds the endTrigger burst stays active. */
    val burstDuration: Float = 0.45f,
    /** Strength multiplier on the burst (added to lift). */
    val burstStrength: Float = 1.6f,
    /** Lateral force amplitude multiplier — higher = more left/right wiggle. */
    val lateralForceScale: Float = 55f,
    /** Wall bounce restitution: 1 = perfectly elastic, 0 = sticks dead. */
    val wallRestitution: Float = 0.85f,
    /** How strongly spin tracks lateral velocity. Higher = ball spins more. */
    val spinFromVelocity: Float = 0.012f,
    /** Spin impulse imparted on each wall hit (in either direction). */
    val wallSpinKick: Float = 0.8f,
) {
    companion object {
        val Default = FloatBallConfig()
    }
}

@Composable
fun FloatBall(
    breath: Float,
    endTrigger: Int,
    modifier: Modifier = Modifier,
    palette: FloatBallPalette = FloatBallPalette.Default,
    config: FloatBallConfig = FloatBallConfig.Default,
) {
    val state = remember { FloatBallSimState() }
    val frameTime = remember { mutableFloatStateOf(0f) }
    val lastTime = remember { mutableFloatStateOf(-1f) }
    val triggerCount = remember { mutableIntStateOf(0) }

    val currentBreath = rememberUpdatedState(breath)
    val currentConfig = rememberUpdatedState(config)

    LaunchedEffect(Unit) {
        var startNanos = 0L
        while (true) {
            withFrameNanos { now ->
                if (startNanos == 0L) startNanos = now
                val tSec = (now - startNanos) / 1_000_000_000f
                val prev = lastTime.floatValue
                val dt = if (prev < 0f) 0f else (tSec - prev).coerceAtMost(0.05f)
                lastTime.floatValue = tSec
                frameTime.floatValue = tSec

                state.tick(dt = dt, t = tSec, breath = currentBreath.value, config = currentConfig.value)
            }
        }
    }

    LaunchedEffect(endTrigger) {
        if (endTrigger > 0 && endTrigger != triggerCount.intValue) {
            triggerCount.intValue = endTrigger
            state.burstT = config.burstDuration
        }
    }

    Canvas(modifier = modifier) {
        @Suppress("UNUSED_VARIABLE") val now = frameTime.floatValue
        val w = size.width
        val h = size.height
        val cx = w / 2f
        val tubeH = min(config.tubeHeightCap, h * config.tubeHeightFraction)
        val tubeOuterR = config.tubeOuterR
        val tubeWall = config.tubeWall
        val tubeInnerR = tubeOuterR - tubeWall
        // Center the tube vertically so the rig sits in the middle of the
        // canvas rather than pinned to the bottom.
        val tubeTop = (h - tubeH) / 2f
        val groundY = tubeTop + tubeH
        val tubeFloor = groundY - 14f
        val ballR = config.ballR
        val yMax = (tubeH - 60f - ballR).coerceAtLeast(0f)
        val xMax = (tubeInnerR - ballR - 2f).coerceAtLeast(0f)

        // Push geometry into the sim so its physics can clamp/bounce correctly.
        state.yMax = yMax
        state.xMax = xMax

        drawBase(cx, groundY, tubeOuterR + 22f, palette)
        drawTubeBack(cx, tubeTop, tubeOuterR, tubeInnerR, tubeH, palette)

        // Inside the tube: clip so streaks/ball don't leak past the inner walls.
        clipRect(
            left = cx - tubeInnerR,
            top = tubeTop + 4f,
            right = cx + tubeInnerR,
            bottom = tubeTop + tubeH,
        ) {
            drawStreaks(cx, tubeFloor, state.streaks, palette)
            drawBall(
                x = cx + state.ballX,
                y = tubeFloor - state.ballY,
                r = ballR,
                angle = state.ballAngle,
                p = palette,
            )
        }

        drawTubeFront(cx, tubeTop, tubeOuterR, tubeInnerR, tubeH, palette)
    }
}

// ---------- Sim state ----------

private class FloatBallSimState {
    var ballX: Float = 0f
    var ballY: Float = 0f
    var ballVX: Float = 0f
    var ballVY: Float = 0f
    var ballSpin: Float = 0f
    var ballAngle: Float = 0f
    var burstT: Float = 0f
    var streakEmitT: Float = 0f
    val streaks: MutableList<FlowStreak> = mutableListOf()

    // Geometry pushed in by the Canvas block.
    var yMax: Float = 0f
    var xMax: Float = 0f

    fun tick(dt: Float, t: Float, breath: Float, config: FloatBallConfig) {
        val breath01 = (breath / 100f).coerceIn(0f, 1f)
        val burst = if (burstT > 0f) {
            val v = burstT / config.burstDuration
            burstT = (burstT - dt).coerceAtLeast(0f)
            v
        } else 0f
        val lift = breath01 + burst * config.burstStrength

        // Turbulence is fully gated on lift — at breath = 0 (and no burst)
        // there's no airflow, so jitter / lateral force collapse to zero and
        // the ball can settle on the floor and stop.
        val turbulence = lift * 2.3f
        val heightFrac = (ballY / yMax.coerceAtLeast(1f)).coerceIn(0f, 1f)
        val nearTop = heightFrac.pow(2.2f)
        val danceBoost = 1f + nearTop * 1.6f

        // Vertical: spring toward equilibrium + jitter + occasional gust.
        val targetY = lift * yMax * config.equilibriumFraction
        val verticalDamp = config.verticalDampBase + nearTop * 6f
        val ay = (targetY - ballY) * config.verticalSpring - ballVY * verticalDamp
        val jitterY =
            (sin(t * 7.3f) * 1.4f +
                sin(t * 3.1f + 1.2f) * 2.2f +
                sin(t * 11.2f + 0.7f) * 1.1f +
                sin(t * 1.7f + 2.4f) * 3.0f +
                sin(t * 0.83f + 0.5f) * 4.0f) * turbulence * 22f * (1f - nearTop * 0.7f)
        val gust = if (Random.nextFloat() < config.gustChance) {
            (Random.nextFloat() - 0.3f) * 180f * lift * (1f - nearTop * 0.8f)
        } else 0f
        ballVY += (ay + jitterY + gust) * dt
        ballY += ballVY * dt
        if (ballY < 0f) {
            ballY = 0f
            if (ballVY < 0f) ballVY = -ballVY * 0.35f
        }
        if (ballY > yMax) {
            ballY = yMax
            if (ballVY > 0f) ballVY = -ballVY * 0.2f
        }

        // Horizontal: turbulence walk + restoring force toward center.
        val lateralForce =
            (sin(t * 4.7f + 0.6f) * 1.0f +
                sin(t * 2.3f) * 0.9f +
                sin(t * 8.1f + 1.5f) * 0.6f +
                sin(t * 0.95f + 3.1f) * 1.3f) * turbulence * config.lateralForceScale * danceBoost
        val lateralGust = if (Random.nextFloat() < (config.gustChance + 0.01f)) {
            (Random.nextFloat() - 0.5f) * 220f * lift * danceBoost
        } else 0f
        val center = -ballX * 1.6f
        ballVX += (lateralForce + lateralGust + center) * dt
        ballVX *= exp(-1.1f * dt)
        ballX += ballVX * dt
        if (ballX > xMax) {
            ballX = xMax
            if (ballVX > 0f) {
                ballVX = -ballVX * config.wallRestitution
                ballSpin -= config.wallSpinKick
            }
        } else if (ballX < -xMax) {
            ballX = -xMax
            if (ballVX < 0f) {
                ballVX = -ballVX * config.wallRestitution
                ballSpin += config.wallSpinKick
            }
        }

        // Spin: damp toward something proportional to lateral velocity.
        ballSpin += (ballVX * config.spinFromVelocity - ballSpin) * min(1f, dt * 3f)
        ballAngle += ballSpin * dt

        // Airflow streaks — emit while there is lift.
        streakEmitT -= dt
        val emitRate = 0.05f - lift * 0.025f
        if (lift > 0.05f && streakEmitT <= 0f) {
            // Streaks are emitted in tube-local horizontal coords (centered on cx);
            // we don't have tubeInnerR here so we use a conservative range based on xMax.
            val sx = (Random.nextFloat() - 0.5f) * (xMax + 8f) * 1.6f
            val speed = -(40f + lift * 90f + Random.nextFloat() * 30f)
            val life = 1.2f + Random.nextFloat() * 0.6f
            streaks += FlowStreak(x = sx, y = 4f, life = life, vy = speed)
            streakEmitT = emitRate.coerceAtLeast(0.012f)
        }
        val it = streaks.iterator()
        while (it.hasNext()) {
            val s = it.next()
            s.update(dt, t)
            if (s.life <= 0f || s.y > yMax + 80f) it.remove()
        }
    }
}

private class FlowStreak(
    var x: Float,
    var y: Float,
    var life: Float,
    val vy: Float,
) {
    val maxLife: Float = life
    val len: Float = 8f + Random.nextFloat() * 14f
    val phase: Float = Random.nextFloat() * TWO_PI
    var vx: Float = 0f

    fun update(dt: Float, t: Float) {
        vx = sin(t * 2.2f + phase) * 0.4f
        x += vx * dt * 60f
        y += vy * dt * 60f
        life -= dt
    }
}

// ---------- Drawing helpers (ports of the JSX functions) ----------

private fun DrawScope.drawBase(cx: Float, groundY: Float, halfW: Float, p: FloatBallPalette) {
    drawOval(
        color = Color.Black.copy(alpha = 0.22f),
        topLeft = Offset(cx + 3f - (halfW + 18f), groundY + 8f - 7f),
        size = Size((halfW + 18f) * 2f, 14f),
    )
    val baseH = 18f
    drawOval(
        color = p.base,
        topLeft = Offset(cx - halfW, groundY),
        size = Size(halfW * 2f, baseH),
    )
    drawOval(
        color = p.baseRim,
        topLeft = Offset(cx - (halfW - 1f), groundY - 2f - 6f),
        size = Size((halfW - 1f) * 2f, 12f),
    )
    drawOval(
        color = Color.Black.copy(alpha = 0.22f),
        topLeft = Offset(cx - (halfW - 4f), groundY - 1f - 4.5f),
        size = Size((halfW - 4f) * 2f, 9f),
    )
}

private fun DrawScope.drawTubeBack(
    cx: Float, topY: Float,
    outerR: Float, innerR: Float,
    tubeH: Float, p: FloatBallPalette,
) {
    val rimYR = 5f

    // Translucent body fill — straight cylinder.
    drawRect(
        brush = Brush.horizontalGradient(
            colorStops = arrayOf(
                0f to p.glassShade.copy(alpha = 0.30f),
                0.5f to p.glass.copy(alpha = 0.14f),
                1f to p.glassShade.copy(alpha = 0.30f),
            ),
            startX = cx - outerR,
            endX = cx + outerR,
        ),
        topLeft = Offset(cx - outerR, topY),
        size = Size(outerR * 2f, tubeH),
    )

    // Far (back) inner wall arc — top half only (faint glass tint).
    drawOval(
        color = p.glassShade.copy(alpha = 0.28f),
        topLeft = Offset(cx - innerR, topY + 1f - (rimYR - 1f)),
        size = Size(innerR * 2f, (rimYR - 1f) * 2f),
    )

    // Subtle inner back-wall shading down the column.
    drawRect(
        color = p.glassShade.copy(alpha = 0.10f),
        topLeft = Offset(cx - innerR, topY + 4f),
        size = Size(innerR * 2f, tubeH - 6f),
    )
}

private fun DrawScope.drawTubeFront(
    cx: Float, topY: Float,
    outerR: Float, innerR: Float,
    tubeH: Float, p: FloatBallPalette,
) {
    val bodyTop = topY
    val bodyBottom = topY + tubeH
    val rimYR = 5f
    val rimYRInner = rimYR - 1f

    // Outer side outlines (vertical only — top is OPEN).
    drawLine(
        color = p.glassShade.copy(alpha = 0.7f),
        start = Offset(cx - outerR, bodyTop),
        end = Offset(cx - outerR, bodyBottom),
        strokeWidth = 1.4f,
    )
    drawLine(
        color = p.glassShade.copy(alpha = 0.7f),
        start = Offset(cx + outerR, bodyTop),
        end = Offset(cx + outerR, bodyBottom),
        strokeWidth = 1.4f,
    )

    // Inner-wall edges.
    drawLine(
        color = p.glassShade.copy(alpha = 0.38f),
        start = Offset(cx - innerR, bodyTop + 4f),
        end = Offset(cx - innerR, bodyBottom),
        strokeWidth = 1f,
    )
    drawLine(
        color = p.glassShade.copy(alpha = 0.38f),
        start = Offset(cx + innerR, bodyTop + 4f),
        end = Offset(cx + innerR, bodyBottom),
        strokeWidth = 1f,
    )

    // Bright vertical highlight on the front-left — spans the full glass height
    // so the reflection reads as part of the cylinder, not a floating strip.
    drawRect(
        brush = Brush.horizontalGradient(
            colorStops = arrayOf(
                0f to Color.White.copy(alpha = 0.55f),
                1f to Color.White.copy(alpha = 0f),
            ),
            startX = cx - outerR + 4f,
            endX = cx - outerR + 14f,
        ),
        topLeft = Offset(cx - outerR + 3f, bodyTop),
        size = Size(10f, tubeH),
    )

    // Soft right-side shading inside the wall — same full-height treatment.
    drawRect(
        brush = Brush.horizontalGradient(
            colorStops = arrayOf(
                0f to p.glassShade.copy(alpha = 0f),
                1f to p.glassShade.copy(alpha = 0.45f),
            ),
            startX = cx + outerR - 14f,
            endX = cx + outerR - 2f,
        ),
        topLeft = Offset(cx + outerR - 14f, bodyTop),
        size = Size(12f, tubeH),
    )

    // Open-mouth: faint glass tint inside the inner ellipse.
    drawOval(
        color = p.glass.copy(alpha = 0.22f),
        topLeft = Offset(cx - innerR, bodyTop + 1f - rimYRInner),
        size = Size(innerR * 2f, rimYRInner * 2f),
    )

    // Glass rim donut — outer ellipse minus inner ellipse, even-odd fill.
    val rimDonut = Path().apply {
        fillType = PathFillType.EvenOdd
        addOval(Rect(cx - outerR, bodyTop - rimYR, cx + outerR, bodyTop + rimYR))
        addOval(Rect(cx - innerR, bodyTop + 1f - rimYRInner, cx + innerR, bodyTop + 1f + rimYRInner))
    }
    drawPath(
        path = rimDonut,
        brush = Brush.horizontalGradient(
            colorStops = arrayOf(
                0f to p.glassRim.copy(alpha = 0.85f),
                0.45f to p.glass.copy(alpha = 0.7f),
                1f to p.glassShade.copy(alpha = 0.85f),
            ),
            startX = cx - outerR,
            endX = cx + outerR,
        ),
    )

    // Tiny specular dot on the front-left of the rim.
    withTransform({
        translate(cx - outerR * 0.55f, bodyTop + rimYR * 0.6f)
        rotate(-0.4f * (180f / PI_F), pivot = Offset.Zero)
    }) {
        drawOval(
            color = Color.White.copy(alpha = 0.95f),
            topLeft = Offset(-3f, -1.2f),
            size = Size(6f, 2.4f),
        )
    }

    // Contact shadow at the bottom of the tube.
    drawOval(
        color = Color.Black.copy(alpha = 0.28f),
        topLeft = Offset(cx - innerR, bodyBottom - 1f - 4f),
        size = Size(innerR * 2f, 8f),
    )
    // Faint floor highlight (top half).
    drawOval(
        color = p.glassRim.copy(alpha = 0.18f),
        topLeft = Offset(cx - (innerR - 4f), bodyBottom - 3f - 2.5f),
        size = Size((innerR - 4f) * 2f, 5f),
    )
    // Bottom outer rim line.
    drawOval(
        color = p.glassShade.copy(alpha = 0f), // base layer transparent for stroke fallback
        topLeft = Offset(cx - outerR, bodyBottom - 5f),
        size = Size(outerR * 2f, 10f),
        style = Stroke(width = 1.2f),
    )
}

private fun DrawScope.drawStreaks(cx: Float, floorY: Float, streaks: List<FlowStreak>, p: FloatBallPalette) {
    for (s in streaks) {
        val alpha = (s.life / s.maxLife).coerceIn(0f, 1f) * 0.55f
        val x = cx + s.x
        val y = floorY - s.y
        drawLine(
            color = p.flow.copy(alpha = alpha),
            start = Offset(x, y),
            end = Offset(x + s.vx * 0.4f, y + s.len),
            strokeWidth = 1.4f,
            cap = StrokeCap.Round,
        )
    }
}

private fun DrawScope.drawBall(
    x: Float, y: Float, r: Float, angle: Float, p: FloatBallPalette,
) {
    // Sphere body — radial gradient from highlight side.
    drawCircle(
        brush = Brush.radialGradient(
            colorStops = arrayOf(
                0f to p.ballHi,
                0.45f to p.ball,
                1f to p.ballShade,
            ),
            center = Offset(x - r * 0.35f, y - r * 0.35f),
            radius = r * 1.3f,
        ),
        radius = r,
        center = Offset(x, y),
    )

    // Equator stripe — rotates with ball, shows spin.
    withTransform({
        translate(x, y)
        rotate(angle * (180f / PI_F), pivot = Offset.Zero)
    }) {
        // Stripe as a path so it can be drawn as a stroked ellipse.
        val stripe = Path().apply {
            addOval(Rect(-r * 0.85f, -r * 0.18f, r * 0.85f, r * 0.18f))
        }
        drawPath(
            path = stripe,
            color = Color.Black.copy(alpha = 0.15f),
            style = Stroke(width = 1.3f),
        )
        // Spin marker dot.
        drawCircle(
            color = Color.Black.copy(alpha = 0.22f),
            radius = 2.2f,
            center = Offset(r * 0.55f, 0f),
        )
    }

    // Specular highlight (tilted ellipse).
    withTransform({
        translate(x - r * 0.4f, y - r * 0.45f)
        rotate(-0.5f * (180f / PI_F), pivot = Offset.Zero)
    }) {
        drawOval(
            color = Color.White.copy(alpha = 0.55f),
            topLeft = Offset(-r * 0.28f, -r * 0.18f),
            size = Size(r * 0.56f, r * 0.36f),
        )
    }
}

