package com.cloudhaus.sensorapp.ui.animation.candle

import androidx.compose.foundation.Canvas
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.mutableFloatStateOf
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberUpdatedState
import androidx.compose.runtime.withFrameNanos
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.drawscope.DrawScope
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.graphics.drawscope.withTransform
import kotlin.math.PI
import kotlin.math.atan2
import kotlin.math.cos
import kotlin.math.exp
import kotlin.math.min
import kotlin.math.sin
import kotlin.random.Random

// Generated by animation-composer/translator from animations/candle/source.jsx,
// then ported by AI from the JSX procedural drawing using the Dandelion port as
// the style exemplar.

private const val TWO_PI = 6.2831855f
// Design canvas — every pixel value below is tuned for this size and scaled
// uniformly to the actual draw area. Matches the workbench preview iframe.
private const val DESIGN_W = 600f
private const val DESIGN_H = 720f

@Suppress("MemberVisibilityCanBePrivate")
data class CandlePalette(
    val candle: Color = Color(0xFFF0E1C6),
    val candleShade: Color = Color(0xFFC9B488),
    val candleRim: Color = Color(0xFFFFF6E2),
    val base: Color = Color(0xFF3A2F24),
    val wick: Color = Color(0xFF2A2118),
    val wickGlow: Color = Color(0xFFFFB347),
    val flameOuter: Color = Color(0xFFFF8B3A),
    val flameInner: Color = Color(0xFFFFD27A),
    val flameCore: Color = Color(0xFFFFFBE2),
    val smoke: Color = Color(0xFFD8D2C4),
) {
    companion object {
        val Default = CandlePalette()
    }
}

@Suppress("MemberVisibilityCanBePrivate")
data class CandleConfig(
    val windStrength: Float = 0.8f,
    val showAxis: Boolean = false,
    val candleWidth: Float = 180f,
    /** Maximum candle height in pixels — actual height is `min(candleHeightCap, h * candleHeightFraction)`. */
    val candleHeightCap: Float = 900f,
    val candleHeightFraction: Float = 0.50f,
    /** Multiplier on the flame's drawn dimensions. */
    val flameSize: Float = 2.5f,
    /** Amplitude of the flicker sin-blend. */
    val flickerStrength: Float = 1f,
    /** Pixel radius of the warm halo around the wick when the flame is full. */
    val haloRadius: Float = 320f,
    /** Normalized breath at which the flame starts guttering (eroding). */
    val gutterStart: Float = 0.7f,
    /** Normalized breath above which erosion accelerates dramatically. */
    val snuffStart: Float = 0.92f,
    /** Seconds of near-zero breath before the wick relights itself. */
    val relightDelay: Float = 0.8f,
    /** How quickly the flame's lean eases toward the breath-driven target. */
    val leanResponseRate: Float = 6f,
    /** Upward acceleration on each smoke puff (per second). Higher = puffs rise faster. */
    val smokeBuoyancy: Float = 1.4f,
) {
    companion object {
        val Default = CandleConfig()
    }
}

@Composable
fun Candle(
    breath: Float,
    endTrigger: Int,
    modifier: Modifier = Modifier,
    palette: CandlePalette = CandlePalette.Default,
    config: CandleConfig = CandleConfig.Default,
) {
    val state = remember { CandleSimState() }
    val frameTime = remember { mutableFloatStateOf(0f) }
    val lastTime = remember { mutableFloatStateOf(-1f) }
    val triggerCount = remember { mutableIntStateOf(0) }

    // Frame loop is launched once with key=Unit; latest breath/config must
    // be visible inside the long-running coroutine via rememberUpdatedState.
    val currentBreath = rememberUpdatedState(breath)
    val currentConfig = rememberUpdatedState(config)

    LaunchedEffect(Unit) {
        var startNanos = 0L
        while (true) {
            withFrameNanos { now ->
                if (startNanos == 0L) startNanos = now
                val tSec = (now - startNanos) / 1_000_000_000f
                val prev = lastTime.floatValue
                val dt = if (prev < 0f) 0f else (tSec - prev).coerceAtMost(0.05f)
                lastTime.floatValue = tSec
                frameTime.floatValue = tSec

                state.tick(
                    dt = dt,
                    t = tSec,
                    breath = currentBreath.value,
                    config = currentConfig.value,
                )
            }
        }
    }

    LaunchedEffect(endTrigger) {
        if (endTrigger > 0 && endTrigger != triggerCount.intValue) {
            triggerCount.intValue = endTrigger
            // The actual extinguish happens at the top of the next tick where
            // we know cx and wickTopY (which depend on Canvas size).
            state.pendingExtinguish = true
        }
    }

    Canvas(modifier = modifier) {
        @Suppress("UNUSED_VARIABLE") val now = frameTime.floatValue
        val w = size.width
        val h = size.height
        // Render in a fixed 600x720 design canvas, letterboxed and centered
        // inside the actual draw area. The whole drawing below stays in design
        // coordinates; Compose handles the scale-up to the actual canvas.
        val s = min(w / DESIGN_W, h / DESIGN_H)
        val ox = (w - DESIGN_W * s) / 2f
        val oy = (h - DESIGN_H * s) / 2f

        withTransform({
            translate(ox, oy)
            scale(s, s, pivot = Offset.Zero)
        }) {
        val cx = DESIGN_W / 2f
        val candleW = config.candleWidth
        val candleH = min(config.candleHeightCap, DESIGN_H * config.candleHeightFraction)
        val groundY = DESIGN_H - 80f
        val candleTopY = groundY - candleH
        val wickBaseY = candleTopY + 2f
        val wickTopY = wickBaseY - 16f

        // Push current geometry into the sim so its tick() (run earlier in
        // the frame loop) can resolve a deferred extinguish at the right spot.
        state.lastCx = cx
        state.lastWickTopY = wickTopY

        // Ground shadow under the candle.
        drawOval(
            color = Color.Black.copy(alpha = 0.10f),
            topLeft = Offset(cx - candleW * 0.8f, groundY + 3f),
            size = Size(candleW * 1.6f, 12f),
        )

        // Warm halo around the wick (only when lit).
        if (state.flameHealth > 0.05f) {
            val glowR = config.haloRadius * state.flameHealth
            drawCircle(
                brush = Brush.radialGradient(
                    colorStops = arrayOf(
                        0f to palette.flameOuter.copy(alpha = 0.18f * state.flameHealth),
                        0.4f to palette.flameOuter.copy(alpha = 0.08f * state.flameHealth),
                        1f to palette.flameOuter.copy(alpha = 0f),
                    ),
                    center = Offset(cx, wickTopY),
                    radius = glowR,
                ),
                radius = glowR,
                center = Offset(cx, wickTopY),
            )
        }

        drawCandle(cx, groundY, candleW, candleH, state.flameHealth, palette)
        drawWick(cx, wickBaseY, wickTopY, state.flameHealth, palette)

        if (state.flameHealth > 0.005f) {
            drawFlame(
                cx, wickTopY,
                lean = state.flameLean,
                flicker = state.flicker(config),
                health = state.flameHealth,
                config = config,
                p = palette,
            )
        }

        drawSmoke(state.puffs, palette)
        }
    }
}

// ---------- Sim state ----------

private class CandleSimState {
    var flickerPhase: Float = Random.nextFloat() * TWO_PI
    var flameHealth: Float = 1f
    var flameLean: Float = 0f
    var smokeEmitT: Float = 0f
    var relightT: Float = 0f
    var blewOut: Boolean = false
    var pendingExtinguish: Boolean = false

    val puffs: MutableList<SmokePuff> = mutableListOf()

    // Last known geometry — pushed in by the Canvas block so tick() can
    // resolve a deferred extinguish (which needs cx / wickTopY for smoke).
    var lastCx: Float = 0f
    var lastWickTopY: Float = 0f

    fun flicker(config: CandleConfig): Float =
        (sin(flickerPhase) * 0.08f + sin(flickerPhase * 2.3f + 1.1f) * 0.05f) * config.flickerStrength

    fun tick(dt: Float, t: Float, breath: Float, config: CandleConfig) {
        val breathC = breath.coerceIn(0f, 100f)
        val breathN = breathC / 100f

        if (pendingExtinguish) {
            pendingExtinguish = false
            extinguish(lastCx, lastWickTopY)
        }

        // Lean: stronger breath → more lean. Smooth toward target.
        val leanTarget = breathN * 0.9f + config.windStrength * 0.15f
        flameLean += (leanTarget - flameLean) * (1f - exp(-dt * config.leanResponseRate))

        // Flicker phase advances faster with breath.
        flickerPhase += dt * (8f + breathN * 6f)

        // Health: heavy breath erodes; light breath recovers — unless latched out.
        if (!blewOut) {
            if (breathN > config.gutterStart) {
                val rate = if (breathN > config.snuffStart) 4f else 1.2f
                val erode = (breathN - config.gutterStart) * rate
                flameHealth -= erode * dt
            } else {
                flameHealth += dt * 0.5f
            }
            flameHealth = flameHealth.coerceIn(0f, 1f)
            if (flameHealth <= 0.001f) extinguish(lastCx, lastWickTopY)
        } else {
            // Re-light after breath returns to ~0 for a moment.
            if (breath < 5f) {
                relightT += dt
                if (relightT > config.relightDelay) {
                    blewOut = false
                    flameHealth = 0.05f
                    relightT = 0f
                }
            } else {
                relightT = 0f
            }
        }

        // Smoke whisper while extinguished.
        smokeEmitT -= dt
        if (blewOut && smokeEmitT <= 0f && puffs.size < 80) {
            puffs += SmokePuff(
                x = lastCx + (Random.nextFloat() - 0.5f) * 4f,
                y = lastWickTopY + 4f,
                life = 1.6f + Random.nextFloat() * 0.5f,
                vx = (Random.nextFloat() - 0.5f) * 0.4f,
                vy = -0.7f - Random.nextFloat() * 0.3f,
            )
            smokeEmitT = 0.07f + Random.nextFloat() * 0.07f
        }

        val wind = config.windStrength * 0.6f
        val it = puffs.iterator()
        while (it.hasNext()) {
            val p = it.next()
            p.update(dt, t, wind, config.smokeBuoyancy)
            if (p.life <= 0f) it.remove()
        }
    }

    private fun extinguish(cx: Float, wickTopY: Float) {
        if (blewOut) return
        blewOut = true
        flameHealth = 0f
        relightT = 0f
        // Burst of smoke at the moment of snuffing.
        repeat(14) {
            puffs += SmokePuff(
                x = cx + (Random.nextFloat() - 0.5f) * 6f,
                y = wickTopY + (Random.nextFloat() - 0.5f) * 4f,
                life = 1.6f + Random.nextFloat() * 0.5f,
                vx = (Random.nextFloat() - 0.5f) * 0.9f,
                vy = -0.9f - Random.nextFloat() * 0.5f,
            )
        }
    }
}

private class SmokePuff(
    var x: Float,
    var y: Float,
    var life: Float,
    var vx: Float,
    var vy: Float,
) {
    val maxLife: Float = life
    var size: Float = 2f + Random.nextFloat() * 3f
    val phase: Float = Random.nextFloat() * TWO_PI

    fun update(dt: Float, t: Float, wind: Float, buoyancy: Float) {
        val age = 1f - life / maxLife
        val curl = sin(t * 1.6f + phase) * (0.25f + age * 0.45f)
        vx += (curl + wind * 0.4f) * dt
        vx *= 0.95f
        vy -= dt * buoyancy
        vy *= 0.985f
        // Cap terminal rise speed at 4× the configured buoyancy so faster
        // levitation also lifts the cap proportionally — keeps puffs from
        // visually slamming against an invisible ceiling.
        val cap = -(buoyancy * 4f)
        if (vy < cap) vy = cap
        x += vx * dt * 60f
        y += vy * dt * 60f
        size += dt * 6f
        life -= dt * 0.5f
    }
}

// ---------- Drawing helpers (ports of the JSX functions) ----------

private fun DrawScope.drawCandle(
    cx: Float, groundY: Float, w: Float, h: Float,
    flameHealth: Float, p: CandlePalette,
) {
    val top = groundY - h
    val halfW = w / 2f

    // Cast shadow on the ground beneath the candle.
    drawOval(
        color = Color.Black.copy(alpha = 0.22f),
        topLeft = Offset(cx + 3f - (halfW + 14f), groundY - 3f),
        size = Size((halfW + 14f) * 2f, 10f),
    )

    // Body — curved top, slight foot rounding.
    val body = Path().apply {
        moveTo(cx - halfW, top + 6f)
        quadraticBezierTo(cx, top - 4f, cx + halfW, top + 6f)
        lineTo(cx + halfW, groundY - 1f)
        quadraticBezierTo(cx + halfW, groundY + 2f, cx + halfW - 3f, groundY + 2f)
        lineTo(cx - halfW + 3f, groundY + 2f)
        quadraticBezierTo(cx - halfW, groundY + 2f, cx - halfW, groundY - 1f)
        close()
    }
    drawPath(body, color = p.candle)

    // Right shadow band.
    val shade = Path().apply {
        moveTo(cx + halfW * 0.55f, top + 4f)
        lineTo(cx + halfW, top + 6f)
        lineTo(cx + halfW, groundY)
        lineTo(cx + halfW * 0.55f, groundY)
        close()
    }
    drawPath(shade, color = p.candleShade)

    // Left rim highlight.
    drawRect(
        color = p.candleRim,
        topLeft = Offset(cx - halfW + 3f, top + 8f),
        size = Size(4f, h - 14f),
    )

    // Top dish (well around the wick) — darker when lit (melted wax).
    drawOval(
        color = if (flameHealth > 0.1f) p.candleShade else p.candleRim,
        topLeft = Offset(cx - (halfW - 4f), top + 4f - 6f),
        size = Size((halfW - 4f) * 2f, 12f),
    )

    // Soft top highlight.
    drawOval(
        color = p.candleRim,
        topLeft = Offset(cx - 2f - (halfW - 10f), top + 2f - 3f),
        size = Size((halfW - 10f) * 2f, 6f),
    )

    // Soft contact shade where the candle meets the ground.
    drawRect(
        brush = Brush.verticalGradient(
            colorStops = arrayOf(
                0f to Color.Black.copy(alpha = 0f),
                1f to Color.Black.copy(alpha = 0.25f),
            ),
            startY = groundY - 8f,
            endY = groundY + 2f,
        ),
        topLeft = Offset(cx - halfW + 1f, groundY - 8f),
        size = Size(w - 2f, 10f),
    )
}

private fun DrawScope.drawWick(
    cx: Float, baseY: Float, topY: Float, flameHealth: Float, p: CandlePalette,
) {
    val lit = flameHealth > 0.05f
    val stalk = Path().apply {
        moveTo(cx, baseY)
        lineTo(cx, topY)
    }
    drawPath(
        path = stalk,
        color = if (lit) p.wickGlow else p.wick,
        style = Stroke(width = 2f, cap = StrokeCap.Round),
    )
    drawCircle(color = p.wick, radius = 1.6f, center = Offset(cx, topY))
}

private fun DrawScope.drawFlame(
    cx: Float, topY: Float,
    lean: Float, flicker: Float, health: Float,
    config: CandleConfig, p: CandlePalette,
) {
    val baseScale = (0.5f + health * 0.85f + flicker * 0.35f * health) * config.flameSize
    val baseW = 11f * baseScale
    val flameH = 44f * baseScale

    val tipDX = lean * flameH * 0.55f
    val tipDY = -flameH

    withTransform({ translate(cx, topY) }) {
        val leftBow = -baseW * (1f - lean * 0.35f)
        val rightBow = baseW * (1f + lean * 0.45f)
        val midY = -flameH * 0.45f

        // Outer flame — radial gradient, asymmetric teardrop.
        val outerPath = Path().apply {
            moveTo(0f, 3f)
            cubicTo(
                leftBow * 0.9f, -flameH * 0.15f,
                tipDX + leftBow * 0.35f, tipDY + flameH * 0.30f,
                tipDX, tipDY,
            )
            cubicTo(
                tipDX + rightBow * 0.35f, tipDY + flameH * 0.30f,
                rightBow * 0.9f, -flameH * 0.15f,
                0f, 3f,
            )
            close()
        }
        drawPath(
            path = outerPath,
            brush = Brush.radialGradient(
                colorStops = arrayOf(
                    0f to p.flameInner.copy(alpha = 0.95f),
                    0.55f to p.flameOuter.copy(alpha = 0.95f),
                    1f to p.flameOuter.copy(alpha = 0f),
                ),
                center = Offset(tipDX * 0.3f, midY),
                radius = flameH * 0.95f,
            ),
        )

        // Cool blue base — thin bluish glow at the wick.
        if (health > 0.2f) {
            val blueR = baseW * 1.2f
            drawOval(
                brush = Brush.radialGradient(
                    colorStops = arrayOf(
                        0f to Color(0xFF7AC8FF).copy(alpha = 0.55f * health),
                        0.6f to Color(0xFF7AC8FF).copy(alpha = 0.18f * health),
                        1f to Color(0xFF7AC8FF).copy(alpha = 0f),
                    ),
                    center = Offset.Zero,
                    radius = blueR,
                ),
                topLeft = Offset(-baseW * 1.1f, -baseW * 0.7f),
                size = Size(baseW * 2.2f, baseW * 1.4f),
            )
        }

        // Inner flame — brighter, tighter teardrop.
        val innerH = flameH * 0.68f
        val innerW = baseW * 0.55f
        val innerTipDX = tipDX * 0.7f
        val innerTipDY = -innerH
        val innerLeft = -innerW * (1f - lean * 0.35f)
        val innerRight = innerW * (1f + lean * 0.45f)
        val innerPath = Path().apply {
            moveTo(0f, 1f)
            cubicTo(
                innerLeft * 0.9f, -innerH * 0.18f,
                innerTipDX + innerLeft * 0.4f, innerTipDY + innerH * 0.32f,
                innerTipDX, innerTipDY,
            )
            cubicTo(
                innerTipDX + innerRight * 0.4f, innerTipDY + innerH * 0.32f,
                innerRight * 0.9f, -innerH * 0.18f,
                0f, 1f,
            )
            close()
        }
        drawPath(innerPath, color = p.flameInner)

        // Hot core — small white-yellow blob, rotated to match the flame's lean.
        val coreY = -flameH * 0.30f
        val coreX = tipDX * 0.3f
        val coreAngleRad = atan2(tipDX, flameH)
        val coreAngleDeg = coreAngleRad * (180f / PI.toFloat())
        withTransform({
            translate(coreX, coreY)
            rotate(coreAngleDeg, pivot = Offset.Zero)
        }) {
            drawOval(
                color = p.flameCore.copy(alpha = 0.85f * health),
                topLeft = Offset(-innerW * 0.40f, -innerH * 0.28f),
                size = Size(innerW * 0.80f, innerH * 0.56f),
            )
        }
    }
}

private fun DrawScope.drawSmoke(puffs: List<SmokePuff>, p: CandlePalette) {
    for (puff in puffs) {
        val a = (puff.life / puff.maxLife).coerceIn(0f, 1f) * 0.4f
        drawCircle(
            color = p.smoke.copy(alpha = a),
            radius = puff.size,
            center = Offset(puff.x, puff.y),
        )
    }
}
