package com.cloudhaus.sensorapp.ui.animation.pinwheel

import androidx.compose.foundation.Canvas
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.mutableFloatStateOf
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberUpdatedState
import androidx.compose.runtime.withFrameNanos
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.drawscope.DrawScope
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.graphics.drawscope.withTransform
import kotlin.math.PI
import kotlin.math.abs
import kotlin.math.cos
import kotlin.math.exp
import kotlin.math.min
import kotlin.math.sin

// Generated by animation-composer/translator from animations/pinwheel/source.jsx,
// then ported by AI from the JSX procedural drawing using the Dandelion port as
// the style exemplar.

private const val TWO_PI = 6.2831855f
private val PI_F = PI.toFloat()
// Design canvas — every pixel value below is tuned for this size and scaled
// uniformly to the actual draw area. Matches the workbench preview iframe.
private const val DESIGN_W = 600f
private const val DESIGN_H = 720f

@Suppress("MemberVisibilityCanBePrivate")
data class PinwheelPalette(
    val stem: Color = Color(0xFF8A6A3D),
    val stemDark: Color = Color(0xFF8D662A),
    val vaneA: Color = Color(0xFF5494E8),
    val vaneB: Color = Color(0xFFC662F4),
    val vaneShade: Color = Color(0xFF2F56B1),
    val hub: Color = Color(0xFFFFFDF8),
    val hubRim: Color = Color(0xFFC9A876),
) {
    companion object {
        val Default = PinwheelPalette()
    }
}

@Suppress("MemberVisibilityCanBePrivate")
data class PinwheelConfig(
    val windStrength: Float = 0.4f,
    val showAxis: Boolean = false,
    val vanes: Int = 4,
    val outerRadius: Float = 152f,
    val hubRadius: Float = 11f,
    val stemWidth: Float = 13f,
    val stemLengthFraction: Float = 0.32f,
    /** Idle drift in rad/s when breath is zero. */
    val idleSpinVelocity: Float = 0.05f,
    /** Spin velocity contribution per unit of normalized breath. */
    val breathToSpinVelocity: Float = 8f,
    /** Spin velocity contribution per unit of (breath * windStrength). */
    val breathWindCoupling: Float = 4f,
    /** Velocity easing rate (1 - exp(-dt * rate)). */
    val spinInertiaRate: Float = 2.2f,
    /** Decay rate of the gust impulse. */
    val gustDecayRate: Float = 1.2f,
    /** Velocity bump on endTrigger. */
    val gustVelocityKick: Float = 18f,
    /** Multiplier on the gust impulse contribution to target velocity. */
    val gustVelocityCoupling: Float = 12f,
) {
    companion object {
        val Default = PinwheelConfig()
    }
}

@Composable
fun Pinwheel(
    breath: Float,
    endTrigger: Int,
    modifier: Modifier = Modifier,
    palette: PinwheelPalette = PinwheelPalette.Default,
    config: PinwheelConfig = PinwheelConfig.Default,
) {
    val frameTime = remember { mutableFloatStateOf(0f) }
    val lastTime = remember { mutableFloatStateOf(-1f) }
    val dtState = remember { mutableFloatStateOf(0f) }
    val spinAngle = remember { mutableFloatStateOf(0f) }
    val spinVel = remember { mutableFloatStateOf(0f) }
    val gust = remember { mutableFloatStateOf(0f) }
    val triggerCount = remember { mutableIntStateOf(0) }

    // The frame loop is launched once with key=Unit, but `breath` and `config`
    // are recomposition inputs that update outside the coroutine. Without
    // rememberUpdatedState the closure captures their initial values forever
    // and the pinwheel never speeds up.
    val currentBreath = rememberUpdatedState(breath)
    val currentConfig = rememberUpdatedState(config)

    LaunchedEffect(Unit) {
        var startNanos = 0L
        while (true) {
            withFrameNanos { now ->
                if (startNanos == 0L) startNanos = now
                val tSec = (now - startNanos) / 1_000_000_000f
                val prev = lastTime.floatValue
                val dt = if (prev < 0f) 0f else (tSec - prev).coerceAtMost(0.05f)
                lastTime.floatValue = tSec
                dtState.floatValue = dt
                frameTime.floatValue = tSec

                // Spin physics — mirrors the JSX tick():
                //   target  = idle + breathN * (breathToSpin + wind*coupling) + gust * gustCoupling
                //   spinVel += (target - spinVel) * (1 - exp(-dt * inertia))
                //   gust    *= exp(-dt * decay)
                //   spinAngle -= spinVel * dt
                val cfg = currentConfig.value
                val breathN = currentBreath.value.coerceIn(0f, 100f) / 100f
                val target = cfg.idleSpinVelocity +
                    breathN * (cfg.breathToSpinVelocity + cfg.windStrength * cfg.breathWindCoupling) +
                    gust.floatValue * cfg.gustVelocityCoupling
                val ease = 1f - exp(-dt * cfg.spinInertiaRate)
                spinVel.floatValue += (target - spinVel.floatValue) * ease
                gust.floatValue *= exp(-dt * cfg.gustDecayRate)
                spinAngle.floatValue -= spinVel.floatValue * dt
            }
        }
    }

    LaunchedEffect(endTrigger) {
        if (endTrigger > 0 && endTrigger != triggerCount.intValue) {
            triggerCount.intValue = endTrigger
            // Wind gust: spike velocity directly + add a decaying impulse.
            spinVel.floatValue += config.gustVelocityKick
            gust.floatValue = 1f
        }
    }

    Canvas(modifier = modifier) {
        // Read frame state to subscribe Canvas to ticks.
        @Suppress("UNUSED_VARIABLE") val now = frameTime.floatValue
        val w = size.width
        val h = size.height
        // Render in a fixed 600x720 design canvas, letterboxed and centered
        // inside the actual draw area. Workbench iframe (~600x720) renders 1:1;
        // a tall phone screen scales the design area up and centers it
        // vertically, so absolute pixel sizes (vane radius, stem width) and
        // height-relative ones (stem length) stay proportional to the design.
        val s = min(w / DESIGN_W, h / DESIGN_H)
        val ox = (w - DESIGN_W * s) / 2f
        val oy = (h - DESIGN_H * s) / 2f

        withTransform({
            translate(ox, oy)
            scale(s, s, pivot = Offset.Zero)
        }) {
            val baseX = DESIGN_W / 2f
            val baseY = DESIGN_H - 80f
            val stemLen = DESIGN_H * config.stemLengthFraction
            val headX = baseX
            val headY = baseY - stemLen

            drawStemAndLeaves(
                baseX = baseX, baseY = baseY,
                headX = headX, headY = headY,
                p = palette, config = config,
            )
            drawPinwheel(
                cx = headX, cy = headY,
                spinAngle = spinAngle.floatValue,
                spinVel = spinVel.floatValue,
                p = palette, config = config,
            )
        }
    }
}

// ---------- Drawing helpers (ports of the JSX functions) ----------

private fun DrawScope.drawStemAndLeaves(
    baseX: Float, baseY: Float,
    headX: Float, headY: Float,
    p: PinwheelPalette,
    config: PinwheelConfig,
) {
    drawOval(
        color = Color.Black.copy(alpha = 0.08f),
        topLeft = Offset(baseX - 18f, baseY + 2f),
        size = Size(36f, 8f),
    )

    val stem = Path().apply {
        moveTo(headX, headY)
        lineTo(baseX, baseY)
    }
    drawPath(
        path = stem,
        color = p.stem,
        style = Stroke(width = config.stemWidth, cap = StrokeCap.Round),
    )

    val highlight = Path().apply {
        moveTo(headX - 2f, headY)
        lineTo(baseX - 2f, baseY)
    }
    drawPath(
        path = highlight,
        color = Color.White.copy(alpha = 0.22f),
        style = Stroke(width = 1.6f, cap = StrokeCap.Round),
    )

    val darkEdge = Path().apply {
        moveTo(headX + 2f, headY)
        lineTo(baseX + 2f, baseY)
    }
    drawPath(
        path = darkEdge,
        color = p.stemDark.copy(alpha = 0.5f),
        style = Stroke(width = 1.4f, cap = StrokeCap.Round),
    )
}

private fun DrawScope.drawPinwheel(
    cx: Float, cy: Float,
    spinAngle: Float,
    spinVel: Float,
    p: PinwheelPalette,
    config: PinwheelConfig,
) {
    val r = config.outerRadius
    val hubR = config.hubRadius
    val vanes = config.vanes

    // Motion-blur cue: when spinning fast, draw a faint disc behind the vanes.
    val speedAbs = abs(spinVel)
    if (speedAbs > 6f) {
        val blurAlpha = ((speedAbs - 6f) * 0.03f).coerceAtMost(0.25f)
        drawCircle(
            brush = Brush.radialGradient(
                colorStops = arrayOf(
                    0f to p.vaneA.copy(alpha = blurAlpha * 0.3f),
                    0.6f to p.vaneA.copy(alpha = blurAlpha),
                    1f to p.vaneA.copy(alpha = 0f),
                ),
                center = Offset(cx, cy),
                radius = r,
            ),
            radius = r,
            center = Offset(cx, cy),
        )
    }

    // Vanes — alternate colors so spin reads. Each vane is a curved sail
    // anchored at center with leading-edge bulge and trailing-edge bow-back.
    withTransform({
        translate(cx, cy)
        rotate(spinAngle * (180f / PI_F), pivot = Offset.Zero)
    }) {
        for (i in 0 until vanes) {
            val baseA = i.toFloat() / vanes * TWO_PI
            val nextA = (i + 1).toFloat() / vanes * TWO_PI
            val tipA = baseA + (nextA - baseA) * 0.62f
            val tipR = r

            val tipX = cos(tipA) * tipR
            val tipY = sin(tipA) * tipR
            val edgeAX = cos(baseA) * r * 0.05f
            val edgeAY = sin(baseA) * r * 0.05f
            val edgeBX = cos(nextA) * r * 0.05f
            val edgeBY = sin(nextA) * r * 0.05f

            val bulgeA1 = baseA + (nextA - baseA) * 0.05f
            val bulgeA2 = baseA + (nextA - baseA) * 0.40f
            val bulgeAX1 = cos(bulgeA1) * r * 0.55f
            val bulgeAY1 = sin(bulgeA1) * r * 0.55f
            val bulgeAX2 = cos(bulgeA2) * r * 1.05f
            val bulgeAY2 = sin(bulgeA2) * r * 1.05f

            val bulgeB1 = baseA + (nextA - baseA) * 0.78f
            val bulgeB2 = baseA + (nextA - baseA) * 0.95f
            val bulgeBX1 = cos(bulgeB1) * r * 0.70f
            val bulgeBY1 = sin(bulgeB1) * r * 0.70f
            val bulgeBX2 = cos(bulgeB2) * r * 0.30f
            val bulgeBY2 = sin(bulgeB2) * r * 0.30f

            val fill = if (i % 2 == 0) p.vaneA else p.vaneB

            val light = Path().apply {
                moveTo(edgeAX, edgeAY)
                cubicTo(bulgeAX1, bulgeAY1, bulgeAX2, bulgeAY2, tipX, tipY)
                lineTo(0f, 0f)
                close()
            }
            drawPath(path = light, color = fill)

            val shadow = Path().apply {
                moveTo(0f, 0f)
                lineTo(tipX, tipY)
                cubicTo(bulgeBX1, bulgeBY1, bulgeBX2, bulgeBY2, edgeBX, edgeBY)
                close()
            }
            drawPath(path = shadow, color = p.vaneShade)

            drawLine(
                color = Color.Black.copy(alpha = 0.18f),
                start = Offset.Zero,
                end = Offset(tipX, tipY),
                strokeWidth = 1f,
            )
        }
    }

    // Hub sits on top of the vanes and does NOT rotate — it's the pin head.
    drawCircle(
        color = Color.Black.copy(alpha = 0.18f),
        radius = hubR + 0.5f,
        center = Offset(cx + 1f, cy + 1f),
    )
    drawCircle(color = p.hub, radius = hubR, center = Offset(cx, cy))
    drawCircle(
        color = p.hubRim,
        radius = hubR,
        center = Offset(cx, cy),
        style = Stroke(width = 1.4f),
    )
    drawCircle(
        color = Color.White.copy(alpha = 0.8f),
        radius = hubR * 0.32f,
        center = Offset(cx - hubR * 0.35f, cy - hubR * 0.35f),
    )
}
